[[pages]]
path = "streamlit_app.py"
name = "Welcome!"
icon = ":house:"

[[pages]]
path = "app/page_1.py"
name = "Page 1"
icon = ":nerd_face:"

[[pages]]
path = "app/page_2.py"
name = "xls to xlsx"
icon = ":nerd_face:"

[[pages]]
path = "app/page_3.py"
name = "PDF Compressor"
icon = ":nerd_face:"
